"""init

Revision ID: 7b17c974177e
Revises: 
Create Date: 2025-11-13 20:40:38.027732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b17c974177e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('team_name', sa.String(length=255), nullable=False, comment='Название команды'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата создания'),
    sa.PrimaryKeyConstraint('team_name'),
    sa.UniqueConstraint('team_name', name='uq_teams_team_name'),
    comment='Команды'
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='ID пользователя'),
    sa.Column('username', sa.String(length=255), nullable=False, comment='Имя пользователя'),
    sa.Column('team_name', sa.String(length=255), nullable=False, comment='Название команды'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Флаг активности'),
    sa.ForeignKeyConstraint(['team_name'], ['teams.team_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id', name='uq_users_user_id'),
    comment='Пользователи'
    )
    op.create_index('idx_users_team_active', 'users', ['team_name', 'is_active'], unique=False)
    op.create_table('pull_requests',
    sa.Column('pull_request_id', sa.String(length=255), nullable=False, comment='ID PR'),
    sa.Column('pull_request_name', sa.String(length=500), nullable=False, comment='Название PR'),
    sa.Column('author_id', sa.String(length=255), nullable=False, comment='ID автора'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Статус: OPEN или MERGED'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата создания'),
    sa.Column('merged_at', sa.DateTime(), nullable=True, comment='Дата merge'),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pull_request_id'),
    sa.UniqueConstraint('pull_request_id', name='uq_pull_requests_pr_id'),
    comment="Pull Request'ы"
    )
    op.create_index('idx_pr_author', 'pull_requests', ['author_id'], unique=False)
    op.create_table('pr_reviewers',
    sa.Column('pr_id', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.pull_request_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pr_id', 'reviewer_id')
    )
    op.create_index('idx_pr_reviewers_reviewer', 'pr_reviewers', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pr_reviewers_reviewer', table_name='pr_reviewers')
    op.drop_table('pr_reviewers')
    op.drop_index('idx_pr_author', table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index('idx_users_team_active', table_name='users')
    op.drop_table('users')
    op.drop_table('teams')
    # ### end Alembic commands ###

